jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiry: 3600000      # Access Token: 1시간
  refresh-token-expiry: 604800000   # Refresh Token: 7일

spring:
  security:
    user:
      name: user
      password: ssafy123
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
portone:
  api-key: ${PORTONE_API_KEY}
  secret-key: ${PORTONE_SECRET_KEY}
  store-id: ${PORTONE_STORE_ID}
  channel-key: channel-key-680df6ca-d2e7-4c93-9a7c-bae25c42e559
  base-url: https://api.iamport.kr

logging:
  level:
    com.minjeok4go.petplace.auth: DEBUG
    root: INFO